abstract: UUID URN Namespace
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: URI-urn-uuid
no_index: 
  directory: 
    - inc
    - t
requires: 
  Data::UUID: 0
version: 0.01
