---
abstract: 'UUID URN Namespace'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-urn-uuid
no_index:
  directory:
    - inc
    - t
requires:
  Data::UUID: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
